/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoADatos.MiembroData;
import Modelo.Miembro;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class VistaMiembro extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewEquipo
     * 
     */
    Miembro miembro=new Miembro();
    MiembroData miData= new MiembroData();
    
    public VistaMiembro() {
        initComponents();
        jrbAlta.setSelected(false); 
        jrbModificar.setSelected(false);
        jtfNombre.setEnabled(false);
        jtfApellido.setEnabled(false);
        jtfDni.setEnabled(false);
        jrbActivo.setEnabled(false);
        jrbInactivo.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbBuscar.setEnabled(false);
        jlDni.setVisible(false);
        jlApellido.setVisible(false);
        jlNombre.setVisible(false);
        
        
    }
    
   public int validar(){
      String texto;
      int nro = 0;
      String textNumber= jtfDni.getText().trim();
      try{
      if(textNumber.isEmpty()){
       jtfDni.requestFocus();
       jlDni.setVisible(true);
      }
      else{
          jlDni.setVisible(false);
          //texto= jtfDni.getText().trim();
      
          nro= Integer.parseInt(textNumber);
          //verificarVacio();
      
      return nro;
      }
      }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "El valor ingresado no es númerico "+ e.getMessage());
        jtfDni.setText(null);
        jtfDni.requestFocus();
      }
      
      return nro;
  }
  
 public boolean verificarVacio() {
    boolean isApellidoEmpty = jtfApellido.getText().isEmpty();
    boolean isNombreEmpty = jtfNombre.getText().isEmpty();

    jtfApellido.requestFocus();
    jlApellido.setVisible(isApellidoEmpty);

    if (!isApellidoEmpty) {
        jtfNombre.requestFocus();
        jlNombre.setVisible(isNombreEmpty);
    }
    
    return (!isApellidoEmpty && !isNombreEmpty);
     
    
}
    
    public boolean verificar(){
     int campos=0, validar;
     try{
     if(jrbAlta.isSelected() || jrbModificar.isSelected()){
       
         validar= Integer.parseInt(jtfDni.getText());
         campos++; //1
         if(!jtfApellido.getText().isEmpty()){
             campos++; //2
         }
         if(!jtfNombre.getText().isEmpty()){
          campos++; //3
         }
         if(campos==3){
          return true;
         }
       }
     else{
       return false; // return false
     }
     } catch(NumberFormatException num){
         JOptionPane.showMessageDialog(null, "El valor ingresado no es un número"+num.getMessage());
       }
       catch(Exception e){
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos"+e.getMessage());
       }
        //return false; //return false
        return false;
     }

    public void darAltaMiembro(){
    if(verificar()){
         miembro.setDni(Integer.parseInt(jtfDni.getText()));
         miembro.setApellido(jtfApellido.getText());
         miembro.setNombre(jtfNombre.getText());
         miembro.setEstado(1); // siempre se da de alta un miembro como activo
         miData.guardarMiembro(miembro);
        }
//        else{
//          JOptionPane.showMessageDialog(null, "Verifique los campos");
////          
//        }
    }
    
    public void limpiar(){
        jrbAlta.setEnabled(true);
        jrbAlta.setSelected(false);
        jrbModificar.setSelected(false);
        jtfDni.setText(null);
        jtfApellido.setText(null);
        jtfNombre.setText(null);
        jrbActivo.setSelected(false);
        jrbInactivo.setSelected(false);
    }
    
    public void modificarMiembro(){
    
        if(verificar()){
         miembro.setDni(Integer.parseInt(jtfDni.getText()));
         miembro.setApellido(jtfApellido.getText());
         miembro.setNombre(jtfNombre.getText());
         if(jrbActivo.isSelected()){
         miembro.setEstado(1); // si
         }
         else{
          miembro.setEstado(0);
         }
         //miData. // siempre se da de alta un miembro como activo
         if(miData.modificarMiembro(miembro)){
          JOptionPane.showMessageDialog(null, "Miembro Actualizado");
          limpiar();
         }
         else{
          JOptionPane.showMessageDialog(null, "No se pudo actualizar la información del miembro");
         }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jrbAlta = new javax.swing.JRadioButton();
        jrbModificar = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jbLimpiar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtfDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbModificarMiembro = new javax.swing.JButton();
        jlDni = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jrbEliminar = new javax.swing.JRadioButton();
        jcbMiembros = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(650, 496));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MIEMBRO");

        jrbAlta.setText("Alta");
        jrbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaActionPerformed(evt);
            }
        });

        jrbModificar.setText("Modificar");
        jrbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        jLabel3.setText("Nombre");

        jLabel5.setText("Estado");

        jrbActivo.setText("Activo");
        jrbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActivoActionPerformed(evt);
            }
        });

        jrbInactivo.setText("Inactivo");
        jrbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInactivoActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Salir");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbModificarMiembro.setText("Modificar Miembro");
        jbModificarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMiembroActionPerformed(evt);
            }
        });

        jlDni.setForeground(new java.awt.Color(204, 0, 0));
        jlDni.setText("Ingrese el DNI");

        jlApellido.setForeground(new java.awt.Color(204, 0, 0));
        jlApellido.setText("Ingrese el Apellido");

        jlNombre.setForeground(new java.awt.Color(204, 0, 0));
        jlNombre.setText("Ingrese el Nombre");

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jrbEliminar.setText("Eliminar un Miembro");
        jrbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEliminarActionPerformed(evt);
            }
        });

        jcbMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMiembrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jbEliminar))
                            .addComponent(jrbEliminar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jbLimpiar)
                                    .addGap(45, 45, 45)
                                    .addComponent(jbCancelar)
                                    .addGap(44, 44, 44)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jrbAlta)
                                            .addGap(38, 38, 38)
                                            .addComponent(jrbModificar)
                                            .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jlDni, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbBuscar)
                                    .addGap(160, 160, 160))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87))))
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jbModificarMiembro)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbGuardar)
                                    .addGap(26, 26, 26))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jrbActivo)
                                            .addGap(18, 18, 18)
                                            .addComponent(jrbInactivo)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAlta)
                    .addComponent(jrbModificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jbBuscar)
                        .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jlApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jrbActivo)
                            .addComponent(jrbInactivo))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbGuardar)
                        .addComponent(jbModificarMiembro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbLimpiar))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActivoActionPerformed
        // TODO add your handling code here:
        jrbInactivo.setSelected(false);
        
        
    }//GEN-LAST:event_jrbActivoActionPerformed

    private void jrbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInactivoActionPerformed
        // TODO add your handling code here:
        jrbActivo.setSelected(false);
    }//GEN-LAST:event_jrbInactivoActionPerformed

    private void jrbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaActionPerformed
        // TODO add your handling code here:
        
        jrbModificar.setSelected(false);
        jrbEliminar.setSelected(false);
        jcbMiembros.removeAllItems();
        jtfNombre.setEnabled(true);
        jtfApellido.setEnabled(true);
        jtfDni.setEnabled(true);
        jrbActivo.setSelected(true);
        jrbActivo.setEnabled(true);
        jbBuscar.setEnabled(false);
        jbGuardar.setEnabled(true);
        jbModificarMiembro.setEnabled(false);
    }//GEN-LAST:event_jrbAltaActionPerformed

    
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        
       int n= validar();
       if(n!=0 && verificarVacio()){
         //JOptionPane.showMessageDialog(this, "Alta exitosa");
          //limpiar();
         miembro.setDni(Integer.parseInt(jtfDni.getText()));
         miembro.setApellido(jtfApellido.getText());
         miembro.setNombre(jtfNombre.getText());
         miembro.setEstado(1); // siempre se da de alta un miembro como activo
         if(miData.guardarMiembro(miembro)){  //; 
           limpiar();
         }
         else{
           jtfDni.requestFocus();
           JOptionPane.showMessageDialog(null, "DNI Duplicado",
  "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
         }
          
        }
      
        // if(jrbAlta.isSelected()){
         //darAltaMiembro();
        //}
        //else{
        // modificarMiembro();
         
        
        
        
//        if(verificar() && jrbAlta.isSelected()){
//         miembro.setDni(Integer.parseInt(jtfDni.getText()));
//         miembro.setApellido(jtfApellido.getText());
//         miembro.setNombre(jtfNombre.getText());
//         miembro.setEstado(1); // siempre se da de alta un miembro como activo
//         miData.guardarMiembro(miembro);
//        }
//        else{
//          JOptionPane.showMessageDialog(null, "Verifique los campos");
//
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniActionPerformed
        // TODO add your handling code here:
        try{
        int nro= Integer.parseInt(jtfDni.getText());
        }catch (NumberFormatException e){
         JOptionPane.showMessageDialog(null, "El valor ingresado no es numerico"+e.getMessage());
        }
    }//GEN-LAST:event_jtfDniActionPerformed

    private void jrbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModificarActionPerformed
              
        jrbAlta.setSelected(false);
        //jrbAlta.setEnabled(false);
        jbBuscar.setEnabled(true);
        jtfDni.setEnabled(true);
        jtfApellido.setEnabled(false);
        jtfNombre.setEnabled(false);
        jrbActivo.setEnabled(false);
        jrbInactivo.setEnabled(false);
        jbGuardar.setEnabled(false);
        
        jrbEliminar.setSelected(false);
        jcbMiembros.removeAllItems();
        jbGuardar.setEnabled(true);
        
    }//GEN-LAST:event_jrbModificarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
       jbGuardar.setEnabled(false);
       jtfApellido.setEnabled(true);
       jtfNombre.setEnabled(true);
       jrbActivo.setEnabled(true);
       jrbInactivo.setEnabled(true);
        try{
        if(!jtfDni.getText().isEmpty()){  
        jbModificarMiembro.setEnabled(true);
        int nro= Integer.parseInt(jtfDni.getText());
        //System.out.println("Numero de documento: "+ nro);
        miembro= miData.buscarMiembroDNI(nro);
        jtfApellido.setText(miembro.getApellido());
        jtfNombre.setText(miembro.getNombre());
        if(miembro.getEstado()==1){
         jrbActivo.setSelected(true);
         jrbInactivo.setSelected(false);
        }
        
        else{
          jrbActivo.setSelected(false);
          jrbInactivo.setSelected(true);
        }
        
        }
        }catch (NumberFormatException e){
         JOptionPane.showMessageDialog(null, "El valor ingresado no es numerico"+e.getMessage());
        }
       
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbModificarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMiembroActionPerformed
       
       try{
       if(!jtfDni.getText().isEmpty() && !jtfApellido.getText().isEmpty() && !jtfNombre.getText().isEmpty()){    
          miembro.setDni(Integer.parseInt(jtfDni.getText()));
          miembro.setApellido(jtfApellido.getText());
          miembro.setNombre(jtfNombre.getText());
          if(jrbActivo.isSelected()){
            miembro.setEstado(1);
           }
          else{
            miembro.setEstado(0);
           }
       miData.modificarMiembro(miembro);
       limpiar();
    }//GEN-LAST:event_jbModificarMiembroActionPerformed
       else{
        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
       }
       }
       catch(NumberFormatException e){
      JOptionPane.showMessageDialog(null, "El valor ingresado no es numerico"+e.getMessage());  
    }}
    
    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jrbAlta.setEnabled(true);
        jrbAlta.setSelected(false);
        jrbModificar.setSelected(false);
        jtfDni.setText(null);
        jtfApellido.setText(null);
        jtfNombre.setText(null);
        jrbActivo.setSelected(false);
        jrbInactivo.setSelected(false);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        try{
        if(jcbMiembros.getSelectedItem()!=null){
        miembro= (Miembro) jcbMiembros.getSelectedItem();
        miData.eliminarMiembro(miembro.getIdMiembro());
        jrbEliminar.setSelected(false);
        jcbMiembros.removeAllItems();
        }
        //JOptionPane.showMessageDialog(jlDni, ui);
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jrbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEliminarActionPerformed
        // TODO add your handling code here:
     jrbModificar.setSelected(false);
     jrbAlta.setSelected(false);
     if(jrbEliminar.isSelected()){
      List<Miembro> listaMiembros= miData.recuperarMiembros();
      if(listaMiembros.size()>0){
       for(Miembro m: listaMiembros){
        jcbMiembros.addItem(m);
       }
      }
     }
    }//GEN-LAST:event_jrbEliminarActionPerformed

    private void jcbMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMiembrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMiembrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModificarMiembro;
    private javax.swing.JComboBox<Miembro> jcbMiembros;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JRadioButton jrbAlta;
    private javax.swing.JRadioButton jrbEliminar;
    private javax.swing.JRadioButton jrbInactivo;
    private javax.swing.JRadioButton jrbModificar;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
