/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoADatos.EquipoData;
import AccesoADatos.EquipoMiembrosData;
import AccesoADatos.MiembroData;
import Modelo.Equipo;
import Modelo.EquiposMiembros;
import Modelo.Miembro;
import com.toedter.calendar.JDateChooser;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
//import java.sql.Date;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class VistaModificarMiembroEquipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaModificarMiembroEquipo
     * 
     */
    Equipo equipo= new Equipo();
    EquipoData equiData= new EquipoData();
    Miembro miembro= new Miembro();
    MiembroData miData= new MiembroData();
    EquipoMiembrosData equiMiembrosData= new EquipoMiembrosData();
    EquiposMiembros equiMiembros= new EquiposMiembros();
    EquiposMiembros em= new EquiposMiembros();
    String newRol;
    
    public VistaModificarMiembroEquipo() {
        initComponents();
        llenarComboEquipo();
        jcbEquipos.setSelectedIndex(-1);
        jcbEquipos.setEnabled(false);
        jcbMiembros.setEnabled(false);
        jdcFechaIncorporacion.setEnabled(false);
        jtfRol.setEnabled(false);
        jbEliminar.setEnabled(false);
        jbGuardar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jcbEquipos = new javax.swing.JComboBox<>();
        jcbMiembros = new javax.swing.JComboBox<>();
        jdcFechaIncorporacion = new com.toedter.calendar.JDateChooser();
        jtfRol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbModificar = new javax.swing.JRadioButton();
        jrbEliminar = new javax.swing.JRadioButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 450));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Equipo Miembros");

        jcbEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEquiposActionPerformed(evt);
            }
        });

        jcbMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMiembrosActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un equipo");

        jLabel2.setText("Seleccione un miembro");

        jLabel3.setText("Fecha incorporación");

        jLabel4.setText("Rol");

        jrbModificar.setText("Modificar");
        jrbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModificarActionPerformed(evt);
            }
        });

        jrbEliminar.setText("Eliminar");
        jrbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar Miembro");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jdcFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jrbModificar)
                                .addGap(45, 45, 45)
                                .addComponent(jrbEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jbEliminar)
                                .addGap(40, 40, 40)
                                .addComponent(jbGuardar))
                            .addComponent(jtfRol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jbSalir)
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbModificar)
                    .addComponent(jrbEliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jdcFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jtfRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbSalir)
                    .addComponent(jbEliminar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarComboEquipo(){
     List<Equipo> listaEquipo= equiData.recuperarEquipos();
     if(listaEquipo.size()>0){
      for(Equipo e: listaEquipo){
        jcbEquipos.addItem(e);
      }
     }
     jcbEquipos.setSelectedIndex(-1);
    }
    
    public void llenarComboMiembro(){
     jdcFechaIncorporacion.setDate(null);
     jtfRol.setText(null);
     equipo= (Equipo) jcbEquipos.getSelectedItem();
     jcbMiembros.removeAllItems();
     List<Miembro> listaMiembros= equiMiembrosData.miembrosDelEquipo(equipo.getIdEquipo());
     if(listaMiembros.size()>0){
      for(Miembro m: listaMiembros){
       jcbMiembros.addItem(m);
      }
     }
     jcbMiembros.setSelectedIndex(-1);
    }
    
    public void limpiar(){
     jcbEquipos.removeAllItems();
     jcbMiembros.removeAllItems();
     jdcFechaIncorporacion.setDate(null);
     jtfRol.setText(null);
     jrbModificar.setSelected(false);
     jrbEliminar.setSelected(false);
    }
    
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModificarActionPerformed
        // TODO add your handling code here:
        jrbEliminar.setSelected(false);
        jcbEquipos.setEnabled(true);
    }//GEN-LAST:event_jrbModificarActionPerformed

    private void jcbEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEquiposActionPerformed
        // TODO add your handling code here:
        jdcFechaIncorporacion.setDate(null);
        jtfRol.setText(null);
        if(jcbEquipos.getSelectedItem()!=null){
            jcbMiembros.setEnabled(true);
            llenarComboMiembro();
        }
    }//GEN-LAST:event_jcbEquiposActionPerformed

    private void jcbMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMiembrosActionPerformed
        // TODO add your handling code here:
        if(jcbMiembros.getSelectedItem()!=null){
          jdcFechaIncorporacion.setDate(null);
          jtfRol.setText(null);
          jbGuardar.setEnabled(true);
          jdcFechaIncorporacion.setEnabled(false);
          jtfRol.setEnabled(true);
          miembro= (Miembro) jcbMiembros.getSelectedItem();
          em = equiMiembrosData.EquipoMiembro(equipo.getIdEquipo(), miembro.getIdMiembro()); 
          LocalDate ld= em.getFechaIncorporacion();
          Date date = (Date) Date.from(ld.atStartOfDay(ZoneId.systemDefault()).toInstant());
          jdcFechaIncorporacion.setDate(date); //.setDate(Date.valueOf(em.getFechaIncorporacion()));
          //jdcFechaIncorporacion.setDate(setDate);
          //String rol= em.getRol();
          jtfRol.setText(em.getRol());
          newRol= em.getRol(); //guardo el Rol en una variable String global
          
          if(jrbEliminar.isSelected()){
           jtfRol.setEnabled(false);
           jbEliminar.setEnabled(true);
           jbGuardar.setEnabled(false);
          }
          //JOptionPane.showMessageDialog(this, em.getFechaIncorporacion());
        }
        //jtfRol.setText("Nada de nada");
    }//GEN-LAST:event_jcbMiembrosActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        if(!newRol.equals(jtfRol.getText())){
          em.setEquipo((Equipo) jcbEquipos.getSelectedItem());
          em.setMiembro((Miembro) jcbMiembros.getSelectedItem());
          em.setRol(jtfRol.getText());
          equiMiembrosData.actualizarEquipoMiembro(em);
          JOptionPane.showMessageDialog(this, "Se ha modificado el rol del miembro en el equipo");
          limpiar();
        }
        else{
          jtfRol.requestFocus();
          JOptionPane.showMessageDialog(this, "Ingrese un nuevo Rol si desea modificarlo");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jrbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEliminarActionPerformed
        // TODO add your handling code here:
       jrbModificar.setSelected(false);
        jcbEquipos.setEnabled(true); 
        llenarComboEquipo();
        
    }//GEN-LAST:event_jrbEliminarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        em = equiMiembrosData.EquipoMiembro(equipo.getIdEquipo(), miembro.getIdMiembro());
        equiMiembrosData.eliminarEquipoMiembros(em.getIdMiembroEq());
        JOptionPane.showMessageDialog(this, "Se eliminó el miembro seleccionado del equipo");
        limpiar();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Equipo> jcbEquipos;
    private javax.swing.JComboBox<Miembro> jcbMiembros;
    private com.toedter.calendar.JDateChooser jdcFechaIncorporacion;
    private javax.swing.JRadioButton jrbEliminar;
    private javax.swing.JRadioButton jrbModificar;
    private javax.swing.JTextField jtfRol;
    // End of variables declaration//GEN-END:variables
}
